### PR TITLE
Fix build

### LINKED ISSUE #57: Clean up solution
Remove local user solution files and resharper settings

### PR DESCRIPTION
**Pull request by gareth-gs**
Closes #57

### CODE REVIEW

**Comment by lneir** [comment]
i still see remove messageBus above in commit 0c7c0eb ???

**Comment by gareth-gs** [comment]
yup - I didn't revert that.  I did copy the source from the origin in 5125d25.  It's all back and nothing is missing now.

**Comment by gareth-gs** [comment]
apologies if I did it in an odd way!  Still figuring out the github workflow

**Comment by lneir** [comment]
i guess commit 5125d25 overrides this previous one???

**Comment by gareth-gs** [comment]
yes correct

**Comment by lneir** [comment]
ok, yes just looks little odd.

**Comment by lneir** [comment]
i'll merge.

**Pull request merged**
