### PR TITLE
update msi build to include new cef files

### PR DESCRIPTION
**Pull request by lneir**
update msi builder to include two new cef files: natives_blob.bin and snapshot_blob.bin

### CODE REVIEW

**Comment by vsadda** [comment]
Lynn,

If I am not mistaken, there is another new CEF file : d3dcompiler_47.dll

-Venu

**Comment by lneir** [comment]
in your latest commit i'm only seeing d3dcompiler_43.dll. the commit removed d3dcompiler_46.dll  

previous code had both d3dcompiler_43.dll and d3dcompiler_46.dll.

what is correct version that should be there?

**Comment by lneir** [comment]
Venu... looks like you might have missed committing 47 version.  can you check and do a new PR?

**Comment by vsadda** [comment]
I may have. Let me add that.  D3d__43.dll and d3d__47.dll both need to be there.  D3d*_46.dll is no longer there. I will let you know when I am done.

**Comment by vsadda** [comment]
Lynn,

I see the d3dcompiler_47.dll in the minuet/symphony/CEF3 folder.

-Venu

From: Sadda, Venugopal [Tech]
Sent: Wednesday, June 24, 2015 1:13 PM
To: 'SymphonyOSF/SFE-Minuet-DesktopClient'; SymphonyOSF/SFE-Minuet-DesktopClient
Subject: RE: [SFE-Minuet-DesktopClient] update msi build to include new cef files (#16)

I may have. Let me add that.  D3d__43.dll and d3d__47.dll both need to be there.  D3d*_46.dll is no longer there. I will let you know when I am done.

**Comment by lneir** [comment]
i just did a clean checkout and the file: d3dcompiler_47.dll is not there.  are you sure you committed that file?

**Comment by vsadda** [comment]
I just created a new branch to check in that file and then noticed that it was already there.

**Comment by vsadda** [comment]
I will add and commit that into a new branch.

**Comment by lneir** [comment]
It was not included in your PR for branch: CEFUpgradeAndProcModelChanges.  So looks like you forgot to check in.  You can open a new PR with the missing file.

**Comment by jonmclachlan** [comment]
Looks good. :)

**Pull request merged**
