### PR TITLE
CEF upgrade to v3.2357.1267. Process model change to allow a family o…

### PR DESCRIPTION
**Pull request by vsadda**
…f applications to share a browser process. Memory management changes to unload workingset periodically

### CODE REVIEW

**Comment by vsadda** [comment]
I have added some more changes to address the user agent issue correctly. Please ignore this request. I will generate a new one.

**Comment by lneir** [comment]
Venu, I see a couple of extra files added in CEF3.  Do you know about these?  Are these need to be shipped?

minuet/symphony/CEF3/natives_blob.bin
minuet/symphony/CEF3/snapshot_blob.bin

**Comment by lneir** [comment]
Venu, also in what file did you make change of UA?

**Comment by vsadda** [comment]
1) The changes for UserAgent are made in Paragon.Runtime/ParagonRuntime.cs (look for ProductVersion in CefSettings) and CefGlue/CefRuntime.cs (look for a new property called ChromeVersion)

2) The .bin files are part of the new CEF redistributable. They are needed for CEF to load correctly,

**Comment by lneir** [comment]
looks good.  i'll merge and update build.

**Pull request merged**
