### PR TITLE
Removed the Symphony.pgx code from the Repo

### PR DESCRIPTION
**Pull request by gareth-gs**
We will need a new repo for the symphony pgx code

### CODE REVIEW

**Comment by lneir** [comment]
before we can commit this, we need to have another repo to move the symphony project into.  have you done that?  then we can commit and then finally jenkins needs updating.

**Comment by gareth-gs** [comment]
not yet  - will do this today.  Assume I'm ok to create a new repo?

**Comment by gareth-gs** [comment]
Just checked I don't have the rights to create a private repo.  @lneir can you create the repo and I'll move the files?  I was thinking calling it "SFE-Symphony-DesktopPackage"

**Comment by lneir** [comment]
here is the repo i created... https://github.com/SymphonyOSF/SFE-DesktopClient-pgx

**Comment by gareth-gs** [comment]
Looks like I don't have access... can you add me please?

**Comment by lneir** [comment]
gareth, you should have write access now.  before we merge commit to delete stuff, let make sure and get stuff over into new repo.  then i need to setup jenkins.  then we can merge you commit into this repo to delete.

**Comment by gareth-gs** [comment]
yeah that's fine and confirmed I have access.  Will move that code now.

**Pull request closed without merging**
