### PR TITLE
Added d3dcompiler_47.dll

### PR DESCRIPTION
**Pull request by vsadda**
Added d3dcompiler_47.dll

### CODE REVIEW

**Comment by jonmclachlan** [comment]
Why do we need to ship the direct3d HLSL 3d compiler with paragon?

http://www.freefixer.com/library/file/d3dcompiler_47.dll-170664/

https://msdn.microsoft.com/en-us/library/windows/desktop/bb509633(v=vs.85).aspx

**Comment by vsadda** [comment]
It is part of the CEF redistributable. We bundle CEF redistributable as is with paragon. It’s your call as to whether you package it into the MSI or not.

**Comment by lneir** [comment]
yes we need packaged with msi.  ineeded for gpu acceleration on windows.

**Comment by jonmclachlan** [comment]
Cool

**Pull request merged**
