### PR TITLE
Fix build

### LINKED ISSUE #57: Clean up solution
Remove local user solution files and resharper settings

### PR DESCRIPTION
**Pull request by gareth-gs**
Closes #57

Will need another branch to add a basic sample for the open source code.

Symphony pgx will be handled in the other repo

### CODE REVIEW

**Comment by lneir** [comment]
@gareth-gs looks like messageBus is getting delete - why?

**Comment by gareth-gs** [comment]
Good question.  Venu told me we were only meant to provide the JAR and not the source.  I need to validate but at this time it’s full of GS namespaces and our internal build system.

The jar was meant to be moved to a top level folder.  Looks like I need to force the add.  Do I need to close this PR and do another?

**Comment by lneir** [comment]
the source was already there.  i think we need the source.

**Comment by lneir** [comment]
for now, i would keep the messageBus, can resubmit new pr with it sitll included?

**Comment by gareth-gs** [comment]
yeah that's cool.  Let me do that now.

**Pull request closed without merging**
